version: '3.8'
services:
  vault-ui:
    ports:
      - "8000:8000"
  consul:
    ports:
      - "8500:8500"
  vault:
    image: ghcr.io/opexdev/vault-opex:latest
  postgres-accountant:
    image: ghcr.io/opexdev/postgres-opex:latest
  postgres-eventlog:
    image: ghcr.io/opexdev/postgres-opex:latest
  postgres-auth:
    image: ghcr.io/opexdev/postgres-opex:latest
  postgres-wallet:
    image: ghcr.io/opexdev/postgres-opex:latest
  postgres-api:
    image: ghcr.io/opexdev/postgres-opex:latest
  postgres-bc-gateway:
    image: ghcr.io/opexdev/postgres-opex:latest
  postgres-referral:
    image: ghcr.io/opexdev/postgres-opex:latest
  postgres-payment:
    image: ghcr.io/opexdev/postgres-opex:latest
  accountant:
    image: ghcr.io/opexdev/accountant:latest
  eventlog:
    image: ghcr.io/opexdev/eventlog:latest
  matching-engine:
    image: ghcr.io/opexdev/matching-engine:latest
  matching-gateway:
    image: ghcr.io/opexdev/matching-gateway:latest
  auth:
    image: ghcr.io/opexdev/auth:latest
  wallet:
    image: ghcr.io/opexdev/wallet:latest
  api:
    image: ghcr.io/opexdev/api:latest
  websocket:
    image: ghcr.io/opexdev/websocket:latest
  bc-gateway:
    image: ghcr.io/opexdev/bc-gateway:latest
  storage:
    image: ghcr.io/opexdev/storage:latest
  referral:
    image: ghcr.io/opexdev/referral:latest
  captcha:
    image: ghcr.io/opexdev/captcha:latest
  admin:
    image: ghcr.io/opexdev/admin:latest
  payment:
    image: ghcr.io/opexdev/payment:latest
  nginx:
    image: ghcr.io/opexdev/nginx:latest
    ports:
      - "443:443"
  web-app:
    image: ghcr.io/opexdev/web-app:latest
  admin-panel:
    image: ghcr.io/opexdev/admin-panel:latest
