version: '3.8'
services:
  web-app:
    image: ghcr.io/opexdev/web-app:$TAG
    environment:
      - ENV=$WEB_APP_ENV
      - APP_TITLE=$WEB_APP_TITLE
      - DESCRIPTION=$WEB_APP_DESCRIPTION
      - API_BASE_URL=$API_BASE_URL
      - CLIENT_ID=$CLIENT_ID
      - LOGIN_CLIENT_ID=$CLIENT_LOGIN_ID
      - CLIENT_SECRET=$CLIENT_SECRET
      - MULTI_LANGS_SUPPORT=$MULTI_LANGS_SUPPORT
      - PRELOAD_LANG=$PRELOAD_LANG
      - LANGS_SUPPORT=$LANGS_SUPPORT
      - DEFAULT_THEME=$DEFAULT_THEME
      - REGISTER_EMAIL_ADDRESS=$REGISTER_EMAIL_ADDRESS
      - REFERENCE_FIAT_CURRENCY=$WEB_APP_REFERENCE_FIAT_CURRENCY
      - CALENDAR_TYPE=$WEB_APP_CALENDAR_TYPE
    networks:
      - default
    deploy:
      restart_policy:
        condition: on-failure
  admin-panel:
    image: ghcr.io/opexdev/admin-panel:$TAG
    environment:
      - APP_TITLE=$ADMIN_TITLE
      - DESCRIPTION=$ADMIN_DESCRIPTION
      - API_BASE_URL=$API_BASE_URL
      - FRONT_URL=$ADMIN_FRONT_URL
      - CLIENT_ID=$ADMIN_CLIENT_ID
      - CLIENT_SECRET=$ADMIN_CLIENT_SECRET
      - SUPERSET_URL=$SUPERSET_URL
    networks:
      - default
    deploy:
      restart_policy:
        condition: on-failure
  mobile-app:
    image: ghcr.io/opexdev/mobile-app:$TAG
    environment:
      - ENV=$WEB_APP_ENV
      - APP_TITLE=$WEB_APP_TITLE
      - DESCRIPTION=$WEB_APP_DESCRIPTION
      - API_BASE_URL=$API_BASE_URL
      - CLIENT_ID=$CLIENT_ID
      - LOGIN_CLIENT_ID=$CLIENT_LOGIN_ID
      - CLIENT_SECRET=$CLIENT_SECRET
      - MULTI_LANGS_SUPPORT=$MULTI_LANGS_SUPPORT
      - PRELOAD_LANG=$PRELOAD_LANG
      - LANGS_SUPPORT=$LANGS_SUPPORT
      - DEFAULT_THEME=$DEFAULT_THEME
      - REGISTER_EMAIL_ADDRESS=$REGISTER_EMAIL_ADDRESS
      - REFERENCE_FIAT_CURRENCY=$WEB_APP_REFERENCE_FIAT_CURRENCY
      - CALENDAR_TYPE=$WEB_APP_CALENDAR_TYPE
    networks:
      - default
    deploy:
      restart_policy:
        condition: on-failure
