x-postgres-db: &postgres-db
  image: ghcr.io/opexdev/postgres-opex:$TAG
  environment:
    - POSTGRES_USER=${DB_USER:-opex}
    - POSTGRES_PASSWORD=${DB_PASS:-hiopex}
    - POSTGRES_DB=${DB_USER:-opex}
    - POSTGRES_READ_ONLY_USER=${DB_READ_ONLY_USER:-opex_reader}
    - POSTGRES_READ_ONLY_PASSWORD=${DB_READ_ONLY_PASS:-hiopex}
  networks:
    - opex-dev
  deploy:
    restart_policy:
      condition: on-failure

version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.1.1
    hostname: zookeeper
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-log:/var/lib/zookeeper/log
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_CLIENT_PORT=2181
    networks:
      - opex-dev
    deploy:
      restart_policy:
        condition: on-failure
  kafka-1:
    image: ghcr.io/opexdev/kafka:$TAG
    hostname: kafka-1
    volumes:
      - kafka-1:/var/lib/kafka/data
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_LISTENERS=CLIENT://kafka-1:29092,EXTERNAL://kafka-1:9092
      - KAFKA_ADVERTISED_LISTENERS=CLIENT://kafka-1:29092,EXTERNAL://kafka-1:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_MIN_INSYNC_REPLICAS=1
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_OPTS=-javaagent:/opt/prometheus/jmx-exporter.jar=1234:/opt/prometheus/kafka-jmx-exporter.yml
    depends_on:
      - zookeeper
    networks:
      - opex-dev
    deploy:
      restart_policy:
        condition: on-failure
  kafka-2:
    image: ghcr.io/opexdev/kafka:$TAG
    hostname: kafka-2
    volumes:
      - kafka-2:/var/lib/kafka/data
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_LISTENERS=CLIENT://kafka-2:29092,EXTERNAL://kafka-2:9092
      - KAFKA_ADVERTISED_LISTENERS=CLIENT://kafka-2:29092,EXTERNAL://kafka-2:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_MIN_INSYNC_REPLICAS=1
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_OPTS=-javaagent:/opt/prometheus/jmx-exporter.jar=1234:/opt/prometheus/kafka-jmx-exporter.yml
    depends_on:
      - zookeeper
    networks:
      - opex-dev
    deploy:
      restart_policy:
        condition: on-failure
  kafka-3:
    image: ghcr.io/opexdev/kafka:$TAG
    hostname: kafka-3
    volumes:
      - kafka-3:/var/lib/kafka/data
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_LISTENERS=CLIENT://kafka-3:29092,EXTERNAL://kafka-3:9092
      - KAFKA_ADVERTISED_LISTENERS=CLIENT://kafka-3:29092,EXTERNAL://kafka-3:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_MIN_INSYNC_REPLICAS=1
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_OPTS=-javaagent:/opt/prometheus/jmx-exporter.jar=1234:/opt/prometheus/kafka-jmx-exporter.yml
    depends_on:
      - zookeeper
    networks:
      - opex-dev
    deploy:
      restart_policy:
        condition: on-failure
  akhq:
    image: tchiotludo/akhq:0.20.0
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka-1:29092,kafka-2:29092,kafka-3:29092"
    networks:
      - opex-dev
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    deploy:
      restart_policy:
        condition: on-failure
  vault:
    image: ghcr.io/opexdev/vault-opex:$TAG
    volumes:
      - vault-data:/vault/file
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - PANEL_PASS=${PANEL_PASS}
      - BACKEND_USER=${BACKEND_USER}
      - SMTP_PASS=${SMTP_PASS}
      - DB_USER=${DB_USER:-opex}
      - DB_PASS=${DB_PASS:-hiopex}
      - DB_READ_ONLY_USER=${DB_READ_ONLY_USER:-opex_reader}
      - DB_READ_ONLY_PASS=${DB_READ_ONLY_PASS:-hiopex}
      - KEYCLOAK_ADMIN_USERNAME=${KEYCLOAK_ADMIN_USERNAME:-opex-admin}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD:-hiopex}
      - OPEX_ADMIN_KEYCLOAK_CLIENT_SECRET=${OPEX_ADMIN_KEYCLOAK_CLIENT_SECRET}
      - VANDAR_API_KEY=$VANDAR_API_KEY
    cap_add:
      - IPC_LOCK
    networks:
      - opex-dev
    deploy:
      restart_policy:
        condition: on-failure
  vault-ui:
    image: djenriquez/vault-ui
    environment:
      - VAULT_URL_DEFAULT=http://vault:8200
      - VAULT_AUTH_DEFAULT=USERNAMEPASSWORD
    depends_on:
      - vault
    networks:
      - opex-dev
    deploy:
      restart_policy:
        condition: on-failure
  consul:
    image: hashicorp/consul
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    networks:
      - opex-dev
    deploy:
      restart_policy:
        condition: on-failure
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
      - redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - opex-dev
    deploy:
      restart_policy:
        condition: on-failure
  postgres-accountant:
    <<: *postgres-db
    volumes:
      - accountant-data:/var/lib/postgresql/data/
  postgres-eventlog:
    <<: *postgres-db
    volumes:
      - eventlog-data:/var/lib/postgresql/data/
  postgres-auth:
    <<: *postgres-db
    volumes:
      - auth-data:/var/lib/postgresql/data/
  postgres-wallet:
    <<: *postgres-db
    volumes:
      - wallet-data:/var/lib/postgresql/data/
  postgres-market:
    <<: *postgres-db
    volumes:
      - market-data:/var/lib/postgresql/data/
  postgres-api:
    <<: *postgres-db
    volumes:
      - api-data:/var/lib/postgresql/data/
  accountant:
    image: ghcr.io/opexdev/accountant:$TAG
    environment:
      - JAVA_OPTS=-Xmx256m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - SPRING_PROFILES_ACTIVE=scheduled
      - KAFKA_IP_PORT=kafka-1:29092,kafka-2:29092,kafka-3:29092
      - CONSUL_HOST=consul
      - DB_IP_PORT=postgres-accountant
      - BACKEND_USER=${BACKEND_USER}
      - VAULT_HOST=vault
      - SWAGGER_AUTH_URL=$KEYCLOAK_FRONTEND_URL
      - PREFERENCES=$PREFERENCES
    configs:
      - preferences.yml
    networks:
      - opex-dev
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - wallet
      - consul
      - vault
      - postgres-accountant
    labels:
      collect_logs: "true"
    deploy:
      restart_policy:
        condition: on-failure
  eventlog:
    image: ghcr.io/opexdev/eventlog:$TAG
    environment:
      - JAVA_OPTS=-Xmx256m
      - KAFKA_IP_PORT=kafka-1:29092,kafka-2:29092,kafka-3:29092
      - CONSUL_HOST=consul
      - DB_IP_PORT=postgres-eventlog
      - BACKEND_USER=${BACKEND_USER}
      - VAULT_HOST=vault
    networks:
      - opex-dev
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - consul
      - vault
      - postgres-eventlog
    labels:
      collect_logs: "true"
    deploy:
      restart_policy:
        condition: on-failure
  matching-engine:
    image: ghcr.io/opexdev/matching-engine:$TAG
    environment:
      - JAVA_OPTS=-Xmx256m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - KAFKA_IP_PORT=kafka-1:29092,kafka-2:29092,kafka-3:29092
      - REDIS_HOST=redis
      - PREFERENCES=$PREFERENCES
    configs:
      - preferences.yml
    networks:
      - opex-dev
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - redis
    labels:
      collect_logs: "true"
    deploy:
      restart_policy:
        condition: on-failure
  matching-gateway:
    image: ghcr.io/opexdev/matching-gateway:$TAG
    environment:
      - JAVA_OPTS=-Xmx256m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - KAFKA_IP_PORT=kafka-1:29092,kafka-2:29092,kafka-3:29092
      - CONSUL_HOST=consul
    networks:
      - opex-dev
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - auth
      - consul
      - matching-engine
    labels:
      collect_logs: "true"
    deploy:
      restart_policy:
        condition: on-failure
  auth:
    image: ghcr.io/opexdev/auth:$TAG
    environment:
      - JAVA_OPTS=-Xmx256m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - KAFKA_IP_PORT=kafka-1:29092,kafka-2:29092,kafka-3:29092
      - CONSUL_HOST=consul
      - DB_IP_PORT=postgres-auth
      - BACKEND_USER=$BACKEND_USER
      - ADMIN_URL=$KEYCLOAK_ADMIN_URL
      - FRONTEND_URL=$KEYCLOAK_FRONTEND_URL
      - VERIFY_REDIRECT_URL=$KEYCLOAK_VERIFY_REDIRECT_URL
      - FORGOT_REDIRECT_URL=$KEYCLOAK_FORGOT_REDIRECT_URL
      - VAULT_URL=http://vault:8200
      - VAULT_HOST=vault
      - PREFERENCES=$PREFERENCES
      - APP_NAME=$APP_NAME
      - APP_BASE_URL=$APP_BASE_URL
    configs:
      - preferences.yml
      - whitelist.txt
    depends_on:
      - captcha
      - kafka-1
      - kafka-2
      - kafka-3
      - consul
      - vault
      - postgres-auth
    labels:
      collect_logs: "true"
    networks:
      - opex-dev
    deploy:
      restart_policy:
        condition: on-failure
  wallet:
    image: ghcr.io/opexdev/wallet:$TAG
    environment:
      - JAVA_OPTS=-Xmx256m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - KAFKA_IP_PORT=kafka-1:29092,kafka-2:29092,kafka-3:29092
      - CONSUL_HOST=consul
      - DB_IP_PORT=postgres-wallet
      - BACKEND_USER=${BACKEND_USER}
      - VAULT_HOST=vault
      - SWAGGER_AUTH_URL=$KEYCLOAK_FRONTEND_URL
      - PREFERENCES=$PREFERENCES
    configs:
      - preferences.yml
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - auth
      - consul
      - vault
      - postgres-wallet
    labels:
      collect_logs: "true"
    networks:
      - opex-dev
    deploy:
      restart_policy:
        condition: on-failure
  market:
    image: ghcr.io/opexdev/market:$TAG
    environment:
      - JAVA_OPTS=-Xmx256m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - KAFKA_IP_PORT=kafka-1:29092,kafka-2:29092,kafka-3:29092
      - CONSUL_HOST=consul
      - DB_IP_PORT=postgres-market
      - BACKEND_USER=${BACKEND_USER}
      - VAULT_HOST=vault
      - SWAGGER_AUTH_URL=$KEYCLOAK_FRONTEND_URL
      - PREFERENCES=$PREFERENCES
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - auth
      - consul
      - vault
      - postgres-market
    labels:
      collect_logs: "true"
    networks:
      - opex-dev
    deploy:
      restart_policy:
        condition: on-failure
  api:
    image: ghcr.io/opexdev/api:$TAG
    environment:
      - JAVA_OPTS=-Xmx256m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - KAFKA_IP_PORT=kafka-1:29092,kafka-2:29092,kafka-3:29092
      - CONSUL_HOST=consul
      - DB_IP_PORT=postgres-api
      - BACKEND_USER=${BACKEND_USER}
      - VAULT_HOST=vault
      - SWAGGER_AUTH_URL=$KEYCLOAK_FRONTEND_URL
      - PREFERENCES=$PREFERENCES
      - API_KEY_CLIENT_SECRET=$API_KEY_CLIENT_SECRET
    configs:
      - preferences.yml
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - accountant
      - matching-gateway
      - market
      - wallet
      - bc-gateway
      - auth
      - referral
      - consul
      - vault
      - postgres-api
    labels:
      collect_logs: "true"
    networks:
      - opex-dev
    deploy:
      restart_policy:
        condition: on-failure
volumes:
  zookeeper-data:
  zookeeper-log:
  kafka-1:
  kafka-2:
  kafka-3:
  vault-data:
  redis-data:
  redis.conf:
  accountant-data:
  eventlog-data:
  auth-data:
  wallet-data:
  market-data:
  api-data:
networks:
  opex-dev:
    external:
      name: opex-dev
configs:
  preferences.yml:
    file: preferences.yml
  whitelist.txt:
    file: whitelist.txt