name: Deploy OPEX - Demo

on:
  push:
    branches:
      - main

jobs:
  jenkinsJob:
    name: Deploy OPEX new demo version
    runs-on: ubuntu-20.04
    steps:
      - name: Trigger jenkins job
        uses: appleboy/jenkins-action@master
        with:
          url: ${{ secrets.JENKINS_DEMO_URL }}
          user: ${{ secrets.JENKINS_DEMO_USER }}
          token: ${{ secrets.JENKINS_DEMO_TOKEN }}
          job: "opex-demo"
